const trainData = {
  trains: [
    {
      route: "Lagos - Ibadan Morning Train (LI1)",
      train_type: "120 KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "180 KM",
      stations: [
        {
          no: 1,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "07:42",
          departure: "07:47",
          distance: "20 KM",
        },
        {
          no: 2,
          code: "BRF",
          station: "Babtunde Raji Fashola Station Agege",
          arrival: "08:06",
          departure: "08:09",
          distance: "20 KM",
        },
        {
          no: 3,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "08:21",
          departure: "08:24",
          distance: "20 KM",
        },
        {
          no: 4,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "08:42",
          departure: "08:45",
          distance: "20 KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "17:07",
          departure: "17:10",
          distance: "20 KM",
        },
        {
          no: 6,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "17:31",
          departure: "17:36",
          distance: "20 KM",
        },
        {
          no: 7,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "17:56",
          departure: "17:58",
          distance: "20 KM",
        },
        {
          no: 8,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "18:12",
          departure: "18:15",
          distance: "20 KM",
        },
        {
          no: 9,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "18:33",
          departure: "18:36",
          distance: "20 KM",
        },
      ],
    },
    {
      route: "Ibadan - Lagos Morning Train (IL2)",
      train_type: "100 KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "180 KM",
      stations: [
        {
          no: 1,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "07:57",
          departure: "08:00",
          distance: "20 KM",
        },
        {
          no: 2,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "08:17",
          departure: "08:20",
          distance: "20 KM",
        },
        {
          no: 3,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "08:35",
          departure: "08:38",
          distance: "20 KM",
        },
        {
          no: 4,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "08:57",
          departure: "09:00",
          distance: "20 KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "09:22",
          departure: "09:25",
          distance: "20 KM",
        },
        {
          no: 6,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "09:33",
          departure: "09:36",
          distance: "20 KM",
        },
        {
          no: 7,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "09:54",
          departure: "09:57",
          distance: "20 KM",
        },
        {
          no: 8,
          code: "BRF",
          station: "Babtunde Raji Fashola Station Agege",
          arrival: "10:09",
          departure: "10:11",
          distance: "20 KM",
        },
        {
          no: 9,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "10:33",
          departure: "10:36",
          distance: "20 KM",
        },
      ],
    },
    {
      route: "Lagos - Ibadan Morning Train (LI3)",
      train_type: "120 KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "180 KM",
      stations: [
        {
          no: 1,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "07:57",
          departure: "08:00",
          distance: "20 KM",
        },
        {
          no: 2,
          code: "BRF",
          station: "Babtunde Raji Fashola Station Agege",
          arrival: "08:21",
          departure: "08:24",
          distance: "20 KM",
        },
        {
          no: 3,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "08:36",
          departure: "08:39",
          distance: "20 KM",
        },
        {
          no: 4,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "08:57",
          departure: "09:00",
          distance: "20 KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "09:07",
          departure: "09:10",
          distance: "20 KM",
        },
        {
          no: 6,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "09:31",
          departure: "09:36",
          distance: "20 KM",
        },
        {
          no: 7,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "09:55",
          departure: "09:58",
          distance: "20 KM",
        },
        {
          no: 8,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "10:12",
          departure: "10:15",
          distance: "20 KM",
        },
        {
          no: 9,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "10:33",
          departure: "10:36",
          distance: "20 KM",
        },
      ],
    },
    {
      route: "Ibadan - Lagos Morning Train (IL4)",
      train_type: "100 KM",
      total_time: "2 hrs, 21 mins",
      total_distance: "120 KM",
      stations: [
        {
          no: 1,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "10:47",
          departure: "10:50",
          distance: "20 KM",
        },
        {
          no: 2,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "11:07",
          departure: "11:10",
          distance: "20 KM",
        },
        {
          no: 3,
          code: "BRF",
          station: "Babtunde Raji Fashola Station Agege",
          arrival: "12:47",
          departure: "12:50",
          distance: "20 KM",
        },
        {
          no: 4,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "13:11",
          departure: "13:14",
          distance: "20 KM",
        },
      ],
    },
  ],
};

export default trainData;
