const trainData = {
  trains: [
    // 1) LAGOS - IBADAN MORNING TRAIN (LI1)
    {
      route: "Lagos - Ibadan Morning Train (LI1)",
      train_type: "160KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "160KM",
      stations: [
        {
          no: 1,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "07:00",
          departure: "07:03",
          distance: "20KM",
        },
        {
          no: 2,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "07:21",
          departure: "07:24",
          distance: "20KM",
        },
        {
          no: 3,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "07:36",
          departure: "07:39",
          distance: "20KM",
        },
        {
          no: 4,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "07:57",
          departure: "08:00",
          distance: "20KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "08:17",
          departure: "08:20",
          distance: "20KM",
        },
        {
          no: 6,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "08:40",
          departure: "08:43",
          distance: "20KM",
        },
        {
          no: 7,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "09:07",
          departure: "09:10",
          distance: "20KM",
        },
        {
          no: 8,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "09:21",
          departure: "09:24",
          distance: "20KM",
        },
        {
          no: 9,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "09:40",
          departure: "09:43",
          distance: "20KM",
        },
      ],
    },

    // 2) IBADAN - LAGOS MORNING TRAIN (IL2)
    {
      route: "Ibadan - Lagos Morning Train (IL2)",
      train_type: "100KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "160KM",
      stations: [
        {
          no: 1,
          code: "OA",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "07:00",
          departure: "07:03",
          distance: "20KM",
        },
        {
          no: 2,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "07:21",
          departure: "07:24",
          distance: "20KM",
        },
        {
          no: 3,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "07:36",
          departure: "07:39",
          distance: "20KM",
        },
        {
          no: 4,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "07:57",
          departure: "08:00",
          distance: "20KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "08:17",
          departure: "08:20",
          distance: "20KM",
        },
        {
          no: 6,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "08:40",
          departure: "08:43",
          distance: "20KM",
        },
        {
          no: 7,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "09:07",
          departure: "09:10",
          distance: "20KM",
        },
        {
          no: 8,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "09:21",
          departure: "09:24",
          distance: "20KM",
        },
        {
          no: 9,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "09:40",
          departure: "09:43",
          distance: "20KM",
        },
      ],
    },

    // 3) LAGOS - IBADAN MORNING TRAIN (LI3)
    {
      route: "Lagos - Ibadan Morning Train (LI3)",
      train_type: "160KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "160KM",
      stations: [
        {
          no: 1,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "10:00",
          departure: "10:03",
          distance: "20KM",
        },
        {
          no: 2,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "10:21",
          departure: "10:24",
          distance: "20KM",
        },
        {
          no: 3,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "10:36",
          departure: "10:39",
          distance: "20KM",
        },
        {
          no: 4,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "10:57",
          departure: "11:00",
          distance: "20KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "11:17",
          departure: "11:20",
          distance: "20KM",
        },
        {
          no: 6,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "11:40",
          departure: "11:43",
          distance: "20KM",
        },
        {
          no: 7,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "12:07",
          departure: "12:10",
          distance: "20KM",
        },
        {
          no: 8,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "12:21",
          departure: "12:24",
          distance: "20KM",
        },
        {
          no: 9,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "12:40",
          departure: "12:43",
          distance: "20KM",
        },
      ],
    },

    // 4) IBADAN - LAGOS AFTERNOON TRAIN (IL4)
    {
      route: "Ibadan - Lagos Afternoon Train (IL4)",
      train_type: "100KM",
      total_time: "2 hrs, 21 mins",
      total_distance: "120KM",
      stations: [
        {
          no: 1,
          code: "OA",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "11:00",
          departure: "11:03",
          distance: "20KM",
        },
        {
          no: 2,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "11:21",
          departure: "11:24",
          distance: "20KM",
        },
        {
          no: 3,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "12:21",
          departure: "12:24",
          distance: "20KM",
        },
        {
          no: 4,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "12:40",
          departure: "12:43",
          distance: "20KM",
        },
      ],
    },

    // 5) LAGOS - IBADAN AFTERNOON TRAIN (LI5)
    {
      route: "Lagos - Ibadan Afternoon Train (LI5)",
      train_type: "160KM",
      total_time: "2 hrs, 33 mins",
      total_distance: "160KM",
      stations: [
        {
          no: 1,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "13:00",
          departure: "13:03",
          distance: "20KM",
        },
        {
          no: 2,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "13:21",
          departure: "13:24",
          distance: "20KM",
        },
        {
          no: 3,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "13:36",
          departure: "13:39",
          distance: "20KM",
        },
        {
          no: 4,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "13:57",
          departure: "14:00",
          distance: "20KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "14:17",
          departure: "14:20",
          distance: "20KM",
        },
        {
          no: 6,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "14:40",
          departure: "14:43",
          distance: "20KM",
        },
        {
          no: 7,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "15:07",
          departure: "15:10",
          distance: "20KM",
        },
        {
          no: 8,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "15:21",
          departure: "15:24",
          distance: "20KM",
        },
        {
          no: 9,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "15:40",
          departure: "15:43",
          distance: "20KM",
        },
      ],
    },

    // 6) IBADAN - LAGOS EVENING TRAIN (IL4) -- (same code repeated on the timetable)
    {
      route: "Ibadan - Lagos Evening Train (IL4)",
      train_type: "100KM",
      total_time: "2 hrs, 21 mins",
      total_distance: "120KM",
      stations: [
        {
          no: 1,
          code: "OA",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "16:00",
          departure: "16:03",
          distance: "20KM",
        },
        {
          no: 2,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "16:21",
          departure: "16:24",
          distance: "20KM",
        },
        {
          no: 3,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "17:21",
          departure: "17:24",
          distance: "20KM",
        },
        {
          no: 4,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "17:40",
          departure: "17:43",
          distance: "20KM",
        },
      ],
    },

    // 7) LAGOS - IBADAN EVENING TRAIN (LI3) -- (same code repeated on the timetable)
    {
      route: "Lagos - Ibadan Evening Train (LI3)",
      train_type: "190KM",
      total_time: "2 hrs, 28 mins",
      total_distance: "190KM",
      stations: [
        {
          no: 1,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "15:27",
          departure: "15:30",
          distance: "20KM",
        },
        {
          no: 2,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "15:57",
          departure: "16:00",
          distance: "20KM",
        },
        {
          no: 3,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "16:17",
          departure: "16:20",
          distance: "20KM",
        },
        {
          no: 4,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "16:37",
          departure: "16:40",
          distance: "20KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "17:07",
          departure: "17:10",
          distance: "20KM",
        },
        {
          no: 6,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "17:31",
          departure: "17:34",
          distance: "20KM",
        },
        {
          no: 7,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "17:56",
          departure: "17:59",
          distance: "20KM",
        },
        {
          no: 8,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "18:12",
          departure: "18:15",
          distance: "20KM",
        },
        {
          no: 9,
          code: "OO",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "18:33",
          departure: "18:36",
          distance: "20KM",
        },
      ],
    },

    // 8) IBADAN - LAGOS EVENING TRAIN (IL6)
    {
      route: "Ibadan - Lagos Evening Train (IL6)",
      train_type: "100KM",
      total_time: "2 hrs, 18 mins",
      total_distance: "160KM",
      stations: [
        {
          no: 1,
          code: "OA",
          station: "Obafemi Awolowo Station Moniya",
          arrival: "16:27",
          departure: "16:30",
          distance: "20KM",
        },
        {
          no: 2,
          code: "LA",
          station: "Ladoke Akintola Station Omi-Adio",
          arrival: "16:47",
          departure: "16:50",
          distance: "20KM",
        },
        {
          no: 3,
          code: "AOO",
          station: "Aremo Olusegun Osoba Olodo",
          arrival: "17:07",
          departure: "17:10",
          distance: "20KM",
        },
        {
          no: 4,
          code: "PWS",
          station: "Professor Wole Soyinka Station Abeokuta",
          arrival: "17:31",
          departure: "17:34",
          distance: "20KM",
        },
        {
          no: 5,
          code: "OFR",
          station: "Olu Fumilayo Ransome Kuti Papalanto",
          arrival: "17:51",
          departure: "17:54",
          distance: "20KM",
        },
        {
          no: 6,
          code: "PYO",
          station: "Professor Yemi Osinbajo Station Kajola",
          arrival: "18:07",
          departure: "18:10",
          distance: "20KM",
        },
        {
          no: 7,
          code: "LKJ",
          station: "Lateef Kayode Jakande Station Agbado",
          arrival: "18:27",
          departure: "18:30",
          distance: "20KM",
        },
        {
          no: 8,
          code: "BRF",
          station: "Babatunde Raji Fashola Station Agege",
          arrival: "18:47",
          departure: "18:50",
          distance: "20KM",
        },
        {
          no: 9,
          code: "MJS",
          station: "Mobolaji Johnson Station Ebute Metta",
          arrival: "19:07",
          departure: "19:10",
          distance: "20KM",
        },
      ],
    },
  ],
};

export default trainData;
